using MediatR;
using PerformanceRatingSystem.Application.Dtos;

namespace PerformanceRatingSystem.Application.Requests.Commands;

public record CreateEmployeePerformanceIndicatorCommand(EmployeePerformanceIndicatorForCreationDto EmployeePerformanceIndicator) : IRequest;
